name: stoneassemblies-massauth
network: stoneassemblies-massauth-network
services:
- name: stoneassemblies-massauth-rabbitmq
  image: rabbitmq:3.11.17-management
  bindings:
  - name: rabbitmq
    port: 6002
    containerPort: 5672
    protocol: tcp
  - name: https
    port: 6003
    containerPort: 15672
    protocol: http
  env:
  - name: RABBITMQ_DEFAULT_USER
    value: queuedemo
  - name: RABBITMQ_DEFAULT_PASS
    value: queuedemo
  volumes:
  - name: stoneassemblies-massauth-rabbitmq-data
    target: /var/lib/rabbitmq
- name: stoneassemblies-massauth-bank-balance-service
  project: ../../src/StoneAssemblies.MassAuth.Bank.Balance.Services/StoneAssemblies.MassAuth.Bank.Balance.Services.csproj
  replicas: 1
  buildProperties: 
  - name: Configuration
    value: Debug
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: RabbitMQ:Address
    value: rabbitmq://host.docker.internal:6002
  - name: RabbitMQ:Username
    value: queuedemo
  - name: RabbitMQ:Password
    value: queuedemo
  - name: MassAuth:ReturnForbiddanceReason
    value: false
  - name: IdentityServer:Authority
    value: http://host.docker.internal:6005/auth/realms/master
  bindings:
  - port: 6004
    containerPort: 80
    protocol: http
- name: stoneassemblies-massauth-server
  project: ../../src/StoneAssemblies.MassAuth.Server/StoneAssemblies.MassAuth.Server.csproj
  replicas: 1
  buildProperties: 
  - name: Configuration
    value: Debug
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: RabbitMQ:Address
    value: rabbitmq://host.docker.internal:6002
  - name: RabbitMQ:Username
    value: queuedemo
  - name: RabbitMQ:Password
    value: queuedemo
  - name: Extensions:Sources:0:Uri
    value: ../../output/nuget-symbols/
  - name: Extensions:Sources:1:Uri
    value: http://host.docker.internal:8081/repository/nuget.org-proxy/index.json
  - name: Extensions:Packages:0
    value: StoneAssemblies.MassAuth.Bank.Rules
- name:  stoneassemblies-massauth-keycloak
  image: quay.io/keycloak/keycloak:21.0.1
  args: start-dev
  bindings:
  - port: 6005
    containerPort: 8080
    protocol: http
  env:
  - name: DEV_TEST
    value: true
  - name: VERBOSE_LOGGING
    value: true
  - name: DISABLE_TRUST_STORE
    value: true
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: stoneassemblies-123!
  - name: KC_TRANSACTION_XA_ENABLED   
    value: false
  - name: KC_HOSTNAME_STRICT
    value: false
  - name: KC_HTTP_ENABLED
    value: true
  - name: KC_HTTP_PORT
    value: 8080
  - name: KC_HTTP_RELATIVE_PATH
    value: /auth
  - name: KC_PROXY
    value: passthrough
  volumes:
  - name: stoneassemblies-keycloak-data
    target: /opt/keycloak/data/